version: "3.9"

services:
  oracle-db:
    image: gvenzl/oracle-xe:latest
    container_name: oracle-db
    restart: always
    environment:
      ORACLE_PASSWORD: password
      ORACLE_DATABASE: data_processing
      ORACLE_USER: user
    ports:
      - "1521:1521"
    volumes:
      - oracle_data:/opt/oracle/oradata
      - ./docker/init:/container-entrypoint-initdb.d

volumes:
    oracle_data: